# Generated by Django 5.1.4 on 2024-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phona_namber', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Имя пользователя')),
                ('age', models.IntegerField(verbose_name='Bозраст пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
