# Generated by Django 5.1.4 on 2024-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilpsqlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phona_namber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
