# Generated by Django 5.1.4 on 2024-12-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilpsqlapp', '0002_alter_buyer_email_alter_buyer_phona_namber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(db_index=True, max_length=50, verbose_name='продукт')),
                ('prise', models.IntegerField(verbose_name='цена')),
            ],
        ),
    ]
