# Generated by Django 5.1.4 on 2024-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilpsqlapp', '0003_person1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person1',
            name='product',
            field=models.TextField(db_index=True, max_length=20, verbose_name='продукт'),
        ),
    ]
