# Generated by Django 5.1.4 on 2024-12-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilpsqlapp', '0004_alter_person1_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals_in_the_zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=15, verbose_name='название животного')),
                ('animal_feed_kg_1day', models.IntegerField(verbose_name='количество корма на 1 день в кг')),
            ],
        ),
    ]
